[manifest]
version = "1.0.0"
priority = 0


[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "self.config.center.soul_pos or self.config.center.demo"
position = "at"
payload = '''
self.config.center.soul_pos or self.config.center.face_pos or self.config.center.demo
'''
match_indent = true
times = 1